name: Run tests

on:
  push:
  pull_request:
    branches-ignore: [ main ]
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.6"]

    runs-on: ubuntu-latest

    env:
        TWFY_API_KEY: ${{ secrets.TWFY_API_KEY }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry ${{ matrix.poetry-version }}
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install poetry==${{ matrix.poetry-version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m poetry config virtualenvs.create false
        python -m poetry install

    - name: Test with ruff
      shell: bash
      run: |
         python -m ruff check src
         python -m ruff format src --check

    - name: Create temp tables for data testing
      shell: bash
      run: |
         python -m twfy_votes update

    - name: Test with pytest
      shell: bash
      run: |
         python -m pytest -v tests
